<h2>Types of missing values</h2>

- MCAR - Missing comletely at random
- MAR - Missing at random
- MNAR - Missing not at random

<h3>MCAR</h3>

The probability of a value being missed has absolutly no relationship with any variable in dataset.

<h3>MAR<h3>

The missingness is related to observed data, but not the missing values themseleves.

<h3>MNAR</h3>

The missingness depends on itself.

<h2>Handling Missing Values Methods</h2>

1. Removing Missing values

    - Row Deletion
    - Column Deletion

2. Imputation

    - Univariate Imputation
        1. Numerical Value Imputation
        2. Categorical Value Imputation
    - Multivariate Imputation
        1. KNN-Imputation
        2. Iterative Imputation

In [3]:
import pandas as pd
import numpy as np
data = {
    'Name':['Rohan','Krish','Bob','Sohit','Kashish','Mayank'],
    'Age':[24,np.nan,34,23,np.nan,40],
    'Attendance':[100,90,80,np.nan,90,85]
}

df = pd.DataFrame(data)
df

      Name   Age  Attendance
0    Rohan  24.0       100.0
1    Krish   NaN        90.0
2      Bob  34.0        80.0
3    Sohit  23.0         NaN
4  Kashish   NaN        90.0
5   Mayank  40.0        85.0

In [34]:
df.isnull().sum()/len(df)*100

Name           0.000000
Age           33.333333
Attendance    16.666667
Score         50.000000
dtype: float64

<h3>Row deletion</h3>

<strong>When it is good to use</strong>

- Low percentage: if < 5% data is missing
- MCAR: The missingness has no hidden pattern
- Large Dataset: if you have large dataset, e.g: if we have 1 million rows, losing 1000 rows won't hurt

<strong>When not to use it</strong>

- Small dataset
- Bias risk: If only "High income" individuals refused to answer the survey, dropping those rows removes your "high income" representation entirely

In [4]:
df_dropped = df.dropna()

In [5]:
df_dropped

     Name   Age  Attendance
0   Rohan  24.0       100.0
2     Bob  34.0        80.0
5  Mayank  40.0        85.0

In [12]:
df_subset = df.dropna(subset=['Age','Score'])

In [13]:
df_subset

    Name   Age  Attendance  Score
0  Rohan  24.0       100.0   85.0
3  Sohit  23.0         NaN   88.0

In [15]:
dt = {
    'A':[1,np.nan,3,np.nan],
    'B':[4,np.nan,np.nan,np.nan],
    'C':[7,8,9,np.nan]
}
dt = pd.DataFrame(dt)

In [20]:
dt

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  8.0
2  3.0  NaN  9.0
3  NaN  NaN  NaN

In [27]:
dt_thresh = dt.dropna(thresh=1,axis=1)
dt_thresh

     A    B    C
0  1.0  4.0  7.0
1  NaN  NaN  8.0
2  3.0  NaN  9.0
3  NaN  NaN  NaN

<h3>Column Deletion<h3>

<strong>When it is good to Use</strong>

- High missingness: eg > 50,60,...
- Irrelevance: If the feature isn't crucial for the prediction

<strong>When it is not recommended</strong>

- Domain Importance

In [ ]:
g

In [ ]:
missing_pct = df.isnull().mean()*100

In [54]:
limit = 30
cols_to_drop = missing_pct[missing_pct.values>=limit].index

In [55]:
df_reduced = df.drop(columns=cols_to_drop)

In [56]:
df_reduced

      Name  Attendance
0    Rohan       100.0
1    Krish        90.0
2      Bob        80.0
3    Sohit         NaN
4  Kashish        90.0
5   Mayank        85.0