In [1]:
import pandas as pd
import numpy as np
data = {
    'Name':['Rohan','Krish','Bob','Sohit','Kashish','Mayank'],
    'Age':[24,np.nan,34,23,np.nan,40],
    'Attendance':[100,90,80,np.nan,90,85]
}

df = pd.DataFrame(data)

In [2]:
df['Notes'] = [np.nan,"Good",np.nan,np.nan,np.nan,"Average"]

In [3]:
df

      Name   Age  Attendance    Notes
0    Rohan  24.0       100.0      NaN
1    Krish   NaN        90.0     Good
2      Bob  34.0        80.0      NaN
3    Sohit  23.0         NaN      NaN
4  Kashish   NaN        90.0      NaN
5   Mayank  40.0        85.0  Average

In [4]:
df['Age'].mean()

30.25

In [5]:
df['Age_filled'] = df['Age'].fillna(df['Age'].mean())

In [6]:
df

      Name   Age  Attendance    Notes  Age_filled
0    Rohan  24.0       100.0      NaN       24.00
1    Krish   NaN        90.0     Good       30.25
2      Bob  34.0        80.0      NaN       34.00
3    Sohit  23.0         NaN      NaN       23.00
4  Kashish   NaN        90.0      NaN       30.25
5   Mayank  40.0        85.0  Average       40.00

In [7]:
df['Attendance_filled'] = df['Attendance'].fillna(df['Attendance'].median())

In [8]:
df

      Name   Age  Attendance    Notes  Age_filled  Attendance_filled
0    Rohan  24.0       100.0      NaN       24.00              100.0
1    Krish   NaN        90.0     Good       30.25               90.0
2      Bob  34.0        80.0      NaN       34.00               80.0
3    Sohit  23.0         NaN      NaN       23.00               90.0
4  Kashish   NaN        90.0      NaN       30.25               90.0
5   Mayank  40.0        85.0  Average       40.00               85.0

In [9]:
df['Notes_filled'] = df['Notes'].fillna("Not Given")

In [10]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given
1,Krish,NaN,90.0,Good,30.25,90.0,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given
5,Mayank,40.0,85.0,Average,40.00,85.0,Average

In [11]:
df['Age_ffill'] = df['Age'].ffill()

In [12]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled,Age_ffill
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given,24.0
1,Krish,NaN,90.0,Good,30.25,90.0,Good,24.0
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given,34.0
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given,23.0
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given,23.0
5,Mayank,40.0,85.0,Average,40.00,85.0,Average,40.0

In [13]:
df['Attendance_bfill'] = df['Attendance'].bfill()

In [15]:
df['Notes_bfill'] = df['Notes'].bfill()

In [16]:
df

,Name,Age,Attendance,Notes,Age_filled,Attendance_filled,Notes_filled,Age_ffill,Attendance_bfill,Notes_bfill
0,Rohan,24.0,100.0,NaN,24.00,100.0,Not Given,24.0,100.0,Good
1,Krish,NaN,90.0,Good,30.25,90.0,Good,24.0,90.0,Good
2,Bob,34.0,80.0,NaN,34.00,80.0,Not Given,34.0,80.0,Average
3,Sohit,23.0,NaN,NaN,23.00,90.0,Not Given,23.0,90.0,Average
4,Kashish,NaN,90.0,NaN,30.25,90.0,Not Given,23.0,90.0,Average
5,Mayank,40.0,85.0,Average,40.00,85.0,Average,40.0,85.0,Average