<h1>Encoding</h1>

In [6]:
import pandas as pd
import numpy as np

In [7]:
data = {
    "StudentID":np.arange(1,101),
    "Subject":np.random.choice(["Math","DSA","React","Chemistry"],100),
    "Marks":np.random.randint(20,50,100),
    "Education":np.random.choice(['High School','Intermediate','Graduate','Post Graduate'],100)
   
}
df = pd.DataFrame(data)

In [8]:
df.head()

   StudentID    Subject  Marks      Education
0          1      React     40    High School
1          2  Chemistry     48    High School
2          3       Math     49   Intermediate
3          4       Math     27   Intermediate
4          5       Math     44  Post Graduate

<h2>Label Encoder</h2>

In [ ]:
pip install scikit-learn

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

df['Subject_Trasformed'] = le.fit_transform(df['Subject'])

In [12]:
df.head(10)

   StudentID    Subject  Marks      Education  Subject_Trasformed
0          1      React     40    High School                   3
1          2  Chemistry     48    High School                   0
2          3       Math     49   Intermediate                   2
3          4       Math     27   Intermediate                   2
4          5       Math     44  Post Graduate                   2
5          6        DSA     24  Post Graduate                   1
6          7        DSA     37       Graduate                   1
7          8       Math     24   Intermediate                   2
8          9      React     34       Graduate                   3
9         10       Math     28  Post Graduate                   2

<h2>One Hot Encoding</h2>

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
oe = OneHotEncoder()

temp = oe.fit_transform(df[['Subject']]).toarray()

In [19]:
df[["Chemistry",'DSA','Math',"React"]] = temp

In [20]:
df.head(20)

,StudentID,Subject,Marks,Education,Subject_Trasformed,Chemistry,DSA,Math,React
0,1,React,40,High School,3,0.0,0.0,0.0,1.0
1,2,Chemistry,48,High School,0,1.0,0.0,0.0,0.0
2,3,Math,49,Intermediate,2,0.0,0.0,1.0,0.0
3,4,Math,27,Intermediate,2,0.0,0.0,1.0,0.0
4,5,Math,44,Post Graduate,2,0.0,0.0,1.0,0.0
5,6,DSA,24,Post Graduate,1,0.0,1.0,0.0,0.0
6,7,DSA,37,Graduate,1,0.0,1.0,0.0,0.0
7,8,Math,24,Intermediate,2,0.0,0.0,1.0,0.0
8,9,React,34,Graduate,3,0.0,0.0,0.0,1.0
9,10,Math,28,Post Graduate,2,0.0,0.0,1.0,0.0
10,11,Math,37,High School,2,0.0,0.0,1.0,0.0
11,12,Math,37,Intermediate,2,0.0,0.0,1.0,0.0
12,13,React,49,Intermediate,3,0.0,0.0,0.0,1.0
13,14,Math,30,Post Graduate,2,0.0,0.0,1.0,0.0
14,15,Chemistry,30,Post Graduate,0,1.0,0.0,0.0,0.0
15,16,DSA,40,High School,1,0.0,1.0,0.0,0.0
16,17,DSA,44,Intermediate,1,0.0,1.0,0.0,0.0
17,18,Math,37,Intermediate,2,0.0,0.0,1.0,0.0
18,19,Math,37,Graduate,2,0.0,0.0,1.0,0.0
19,20,React,39,Graduate,3,0.0,0.0,0.0,1.0

<h2>Ordinal Encoder</h2>

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [25]:
categories = [["High School","Intermediate","Graduate","Post Graduate"]]


oen = OrdinalEncoder(categories = categories)

df['EducationTransformed'] = oen.fit_transform(df[['Education']])

In [26]:
df.head(20)

,StudentID,Subject,Marks,Education,Subject_Trasformed,Chemistry,DSA,Math,React,EducationTransformed
0,1,React,40,High School,3,0.0,0.0,0.0,1.0,0.0
1,2,Chemistry,48,High School,0,1.0,0.0,0.0,0.0,0.0
2,3,Math,49,Intermediate,2,0.0,0.0,1.0,0.0,1.0
3,4,Math,27,Intermediate,2,0.0,0.0,1.0,0.0,1.0
4,5,Math,44,Post Graduate,2,0.0,0.0,1.0,0.0,3.0
5,6,DSA,24,Post Graduate,1,0.0,1.0,0.0,0.0,3.0
6,7,DSA,37,Graduate,1,0.0,1.0,0.0,0.0,2.0
7,8,Math,24,Intermediate,2,0.0,0.0,1.0,0.0,1.0
8,9,React,34,Graduate,3,0.0,0.0,0.0,1.0,2.0
9,10,Math,28,Post Graduate,2,0.0,0.0,1.0,0.0,3.0
10,11,Math,37,High School,2,0.0,0.0,1.0,0.0,0.0
11,12,Math,37,Intermediate,2,0.0,0.0,1.0,0.0,1.0
12,13,React,49,Intermediate,3,0.0,0.0,0.0,1.0,1.0
13,14,Math,30,Post Graduate,2,0.0,0.0,1.0,0.0,3.0
14,15,Chemistry,30,Post Graduate,0,1.0,0.0,0.0,0.0,3.0
15,16,DSA,40,High School,1,0.0,1.0,0.0,0.0,0.0
16,17,DSA,44,Intermediate,1,0.0,1.0,0.0,0.0,1.0
17,18,Math,37,Intermediate,2,0.0,0.0,1.0,0.0,1.0
18,19,Math,37,Graduate,2,0.0,0.0,1.0,0.0,2.0
19,20,React,39,Graduate,3,0.0,0.0,0.0,1.0,2.0